### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by douglas-srs** [HituziANDO/kamome#4]
Hey,

Can you please add Carthage support?

**Comment by HituziANDO** [comment]
@douglas-srs 

I supported Carthage from ver.3.2.0.

Try to add the following line to your Cartfile.

```
github "HituziANDO/kamome"
```

**Comment by douglas-srs** [comment]
I tried that but I got this error when trying to update carthage with this command: carthage update --platform iOS

```A shell task (/usr/bin/xcrun xcodebuild -project /Users/douglas/Documents/Development/SigiWebiOS/Carthage/Checkouts/kamome/ios/Kamome/Kamome.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'Kamome.xcodeproj' from folder '/Users/douglas/Documents/Development/SigiWebiOS/Carthage/Checkouts/kamome/ios/Kamome'.
	Reason: Project /Users/douglas/Documents/Development/SigiWebiOS/Carthage/Checkouts/kamome/ios/Kamome/Kamome.xcodeproj cannot be opened because it is missing its project.pbxproj file.```

**Comment by HituziANDO** [comment]
I don't know why the first letter of your kamome.xcodeproj file is capital "K", but please delete the Carthage folder and try again.

NOTE: The first letter of kamome.xcodeproj and kamome.framework is lowercase.

**Comment by douglas-srs** [comment]
After removing kamome folder inside Carthage's checkout folder and cleaning carthage cache it worked! Thank you.

Here is the command if anyone needs it: rm -rf ~/Library/Caches/org.carthage.CarthageKit
