### ISSUE TITLE
Manual Installation error

### ISSUE THREAD

**Issue by douglas-srs** [HituziANDO/kamome#5]
Hey,

I am trying to install this manually so I built the Universal target and then added the framework to my project and built it but I get an error when it tries to launch the app: 

`Failed to load Info.plist from bundle at path /Users/douglas/Library/Developer/CoreSimulator/Devices/C5988B06-A755-40CB-9B18-EE4CCF8D1C1D/data/Library/Caches/com.apple.mobile.installd.staging/temp.SVkAJx/extracted/Payload/SigiWeb.app/Frameworks/KamomeSDK.framework
Failed to load Info.plist from bundle at path /Users/douglas/Library/Developer/CoreSimulator/Devices/C5988B06-A755-40CB-9B18-EE4CCF8D1C1D/data/Library/Caches/com.apple.mobile.installd.staging/temp.SVkAJx/extracted/Payload/SigiWeb.app/Frameworks/KamomeSDK.framework`

**Comment by HituziANDO** [comment]
Try following.

1. Product > Clean Build Folder
2. Run

**Comment by douglas-srs** [comment]
I did that, even deleted DerivedData folder and restarted xcode but the error persists.
